config/routes.rb
Rails.application.routes.draw do
  
  root 'homes#index'
  devise_for :users

  resources :users_admin, :controller => 'users' 
  get '/fetch_team' => 'users#fetch_team' 
  get '/send_mail'  => 'users#send_mail'

  post 'compose_email' => "users#compose_email"

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)
      if user.admin?
        Rails.logger.info "=====#{user.inspect}===="
        can :manage, :all
      else
        can :read, :all
      end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/team.rb
class Team < ActiveRecord::Base
	validates_uniqueness_of :first_name, scope: :designation
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  mount_uploader :image, AvatarUploader
  scope :standard_users, -> {where(role: 'standard')}

  def full_name
  	self.first_name+' '+self.last_name
  end   

  def admin?
  	self.role.eql? 'admin'
  end


   
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
    before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:email, :password, :password_confirmation, :first_name, :last_name, :company, :designation, :image, :role) }
    devise_parameter_sanitizer.for(:account_update) do |u|
      u.permit(:email, :password, :password_confirmation, :current_password, :first_name, :last_name, :company, :designation, :image, :role)
    end
  end

  helper_method :is_admin

  def is_admin
  	current_user.admin?
  end	

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, :alert => exception.message
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
require 'nokogiri'
require 'open-uri'
class UsersController < ApplicationController
  #load_and_authorize_resource
	
  def fetch_team
    doc = Nokogiri::HTML(open('http://letsgomo.com/meet-our-team/'))  	 
      doc.css('#content .container div.team-member.one-fourth').each do |record|
  	  image = record.children[0].attributes["src"]
  	  name = record.children[1].children.children.first.text
  	  designation = record.children[1].children.children[1].text
  	  Team.create(first_name: name, picture: image, designation: designation) 
    end
    redirect_to root_path
  end

  def send_mail

  end	

	def index
		@users = User.standard_users
	end 

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		password = (0...50).map { ('a'..'z').to_a[rand(26)] }.join
	  @user.password = password
	  @user.password_confirmation = password

		if @user.save
			redirect_to users_admin_index_path_path, notice: 'User has been successfully created'
		else
			render 'new'
		end	
	end

	def edit
    @user = User.find(params[:id])
	end	

	def show
		@user = User.find(params[:id])
	end	

	def update
    @user = User.find(params[:id])
    params[:user].delete(:password) if params[:user][:password].blank?
    params[:user].delete(:password_confirmation) if params[:user][:password].blank? and params[:user][:password_confirmation].blank?
    if @user.update_attributes(params[:user])
      flash[:notice] = "Successfully updated User."
      redirect_to root_path
    else
      render :action => 'edit'
    end
  end

  def compose_email
  	redirect_to root_path, notice: "Message has been successfully delivered."
  end	

	private
	def user_params
		params.require(:user).permit!
	end	
end

app/helpers/application_helper.rb
module ApplicationHelper

	def teams_email
		Team.all.map{|x| x.first_name.downcase+"@letsgomo.com"}
	end	

	def image_teams 
		Team.all.map{|x| x.first_name+"_"+x.designation}
  end
 
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/index.html.erb
<h1>Homes#index</h1>
<p>Find me in app/views/homes/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Letsgo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if user_signed_in? %>
  <%= link_to 'Log Out', destroy_user_session_path, method: :delete %>|
  <%= link_to "Send Mail", send_mail_path %>
  <%= link_to 'Fetch Team', fetch_team_path %>
  <%= link_to 'Users', users_admin_index_path if is_admin %> |
  <%= link_to current_user.full_name, root_path %>|
  <%= link_to 'Edit Profile', edit_user_registration_path %>
<% else %>
  <%= link_to 'Log In',  new_user_session_path %>
  <%= link_to 'Sign Up', new_user_registration_path %>
<% end %>
  <% if notice %>
    <p class="notice"><%= notice %></p>
  <% elsif alert %>  
    <p class="alert"><%= alert %></p>
  <% end %>
<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for @user, :multipart => true, :url => users_admin_index_path do |f| %>
  
   <% @user.errors.full_messages.each do |msg| %>
      <p><%= msg %></p>
   <% end %>

  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label :company %><br />
    <%= f.text_field :company, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label :designation %><br />
    <%= f.text_field :designation, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label :image %><br />
    <%= f.file_field :image, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email, autofocus: true %>
  </div>

  <% f.hidden_field :role, :value => 'standard' %>

  <%= f.submit "Submit" %>

<% end %>

app/views/users/edit.html.erb
<%= render 'form' %>

app/views/users/index.html.erb
<h1>Users List</h1>

<table id="user" border="3" layout= "fixed" width=" 100%"  >
  <colgroup>
    <col style="width: 33%" />
    <col style="width: 33%" />
    <col style="width: 33%" />

  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Image</th>
    <th> Company</th>
    <th> Designation</th>
    <th>Actions</th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>  
  <tr >
    <td><%= user.full_name %></td>
    <td><%= user.email %></td>
    <td><%=image_tag user.image.url(:thumb)%></td>
    <td><%= user.company %></td>
    <td><%= user.designation %></td>
    <td><%= link_to 'EDIT', root_path %>
        <%= link_to 'VIEW', root_path %></td>
    
  </tr>
<% end %>
 </colgroup>
</table>

<br />

<%= link_to 'ADD New user', new_users_admin_path %>

app/views/users/new.html.erb
<%= render 'form' %>

app/views/users/send_mail.html.erb
<% provide(:title, "Sign in") %>
<h1>Send Message</h1>

<div class="row">
  <div class="span 6 offset 3">
    <%= form_tag  compose_email_path, method: :post do %>

      <%= label_tag :email %>
      <%= select_tag :email, options_for_select(teams_email) %><br/><br/>

      <%= label_tag :message %>
      <%= text_area_tag :message %><br/><br/>

      <%= label_tag :image %>
      <%= select_tag :image, options_for_select(image_teams) %><br/><br/>

      <%= submit_tag "Sign in", class: "btn btn-large btn-primary" %>
    <% end %>

    
  </div>
</div>